version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/brandManager
    networks:
      - mynetwork
    restart: always  

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www  
    depends_on:
      - app
    ports:
      - "8085:80"
    networks:
      - mynetwork
    restart: always  

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brandManager
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    restart: always  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - mynetwork
    restart: always  

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge